picture: agcenable.cpp Lepton_I2C.cpp ./leptonSDKEmb32PUB/crc16fast.c ./leptonSDKEmb32PUB/LEPTON_AGC.c ./leptonSDKEmb32PUB/LEPTON_VID.c ./leptonSDKEmb32PUB/LEPTON_I2C_Protocol.c ./leptonSDKEmb32PUB/LEPTON_I2C_Service.c ./leptonSDKEmb32PUB/raspi_I2C.c ./leptonSDKEmb32PUB/LEPTON_SDK.c ./leptonSDKEmb32PUB/LEPTON_SYS.c

	gcc -o ../agcenable.exe agcenable.cpp Lepton_I2C.cpp ./leptonSDKEmb32PUB/Debug/crc16fast.o ./leptonSDKEmb32PUB/Debug/LEPTON_AGC.o ./leptonSDKEmb32PUB/Debug/LEPTON_VID.o ./leptonSDKEmb32PUB/Debug/LEPTON_I2C_Protocol.o ./leptonSDKEmb32PUB/Debug/LEPTON_I2C_Service.o ./leptonSDKEmb32PUB/Debug/raspi_I2C.o ./leptonSDKEmb32PUB/Debug/LEPTON_SDK.o ./leptonSDKEmb32PUB/Debug/LEPTON_SYS.o -I/usr/include/-I. -I.


